# 网站简介
site_name: WintermelonC Docs
site_url: https://wintermelonc.github.io/WintermelonC_Docs/
site_author: WintermelonC
site_description: WinteremelonC 的网页

# github 仓库
repo_url: https://github.com/WintermelonC/WintermelonC_Docs
repo_name: WintermelonC_Docs
edit_uri: edit/main/docs/

# 页面布局
nav:
  - 首页: index.md
  - ZJU:
    - zju/index.md
    - 思政类:
      - zju/political/index.md
      - 中国共产党历史: zju/political/history_of_CPC.md
    - 军体类:
      - zju/military_PE/index.md
      - 无线电测向（初级）: zju/military_PE/radio_direction_finding.md
      - 羽毛球（初级）: zju/military_PE/badminton.md
      - 军事理论: zju/military_PE/military_theory.md
    - 自然科学通识类:
      - zju/natural_science/index.md
      - 大学物理（乙）Ⅱ: 
        - zju/natural_science/phy_2/index.md
        - 整理: zju/natural_science/phy_2/phy_2_doc.md
      - 大学物理实验: zju/natural_science/phy_exp.md
    - 创新创业类:
      - zju/innovation_entrepreneurship/index.md
      - 创业启程: zju/innovation_entrepreneurship/entrepreneurship.md
    - 通识选修课程:
      - zju/general_courses/index.md
      - 茶文化与茶健康: zju/general_courses/tea_culture.md
      - 经济法理论与实务: zju/general_courses/economic_law.md
      - 生物进化与设计: 
        - zju/general_courses/bio_evolution_and_design/index.md
        - 整理: zju/general_courses/bio_evolution_and_design/doc.md
      - 生命科学导论: zju/general_courses/life_science.md
      - 生命科学导论实验: zju/general_courses/life_science_exp.md
    - 专业基础课程:
      - zju/basic_courses/index.md
      - 数字逻辑设计:
        - zju/basic_courses/digital_logic_design/index.md
        - 实验部分:
          - zju/basic_courses/digital_logic_design/lab/index.md
          - final: zju/basic_courses/digital_logic_design/lab/final.md
      - 概率论与数理统计: 
        - zju/basic_courses/prob_theo_and_math_stat/index.md
        - 2 随机变量及其概率分布: zju/basic_courses/prob_theo_and_math_stat/chapter_2.md
        - 4 随机变量的数字特征: zju/basic_courses/prob_theo_and_math_stat/chapter_4.md
    - 专业必修课程:
      - zju/compulsory_courses/index.md
      - 高级数据结构与算法分析:
        - zju/compulsory_courses/ADS/index.md
        - 1 AVL Trees, Splay Trees and Amortized Analysis: zju/compulsory_courses/ADS/ch1.md
        - 2 Red-Black Trees and B+ Trees: zju/compulsory_courses/ADS/ch2.md
        - 3 Inverted File Index: zju/compulsory_courses/ADS/ch3.md
        - 4 Leftist Heaps and Skew Heaps: zju/compulsory_courses/ADS/ch4.md
        - 5 Binomial Queues: zju/compulsory_courses/ADS/ch5.md
        - 6 Backtracking: zju/compulsory_courses/ADS/ch6.md
        - 7 Divide and Conquer: zju/compulsory_courses/ADS/ch7.md
      - 计算机组成:
        - zju/compulsory_courses/computer_organization/index.md
        - 理论部分: 
          - 1 Computer Abstractions and Technology: zju/compulsory_courses/computer_organization/theory/ch1.md
          - '2 Instructions: Language of the Computer': zju/compulsory_courses/computer_organization/theory/ch2.md
          - 3 Arithmetic for Computers: zju/compulsory_courses/computer_organization/theory/ch3.md
        - 实验部分:
          - zju/compulsory_courses/computer_organization/lab/index.md
    - 实践教学环节:
      - zju/practical_teaching/index.md
      - 课程综合实践Ⅰ: zju/practical_teaching/practical_course_1.md
  - 大学生生活常识:
    - common_sense/index.md
    - 医院看病流程: common_sense/hospital.md
    - 医保: common_sense/medical_insurance.md
    - 如何乘坐交通工具: common_sense/transportation.md
    - 租房流程及注意事项: common_sense/rent.md
  - 常用软件:
    - application/index.md
    - Ps:
      - application/ps/index.md
    - Pr:
      - application/pr/index.md
      - 插件: application/pr/plugins.md
    - Ae:
      - application/ae/index.md
      - 其他:
        - 物体阴影: application/ae/other/shadow.md
      - 插件: application/ae/plugins.md

not_in_nav: |
  /file/*.md

# 主题设置
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换至黑夜模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至白天模式
  language: zh
  logo: ./img/logo.png
  favicon: ./img/logo.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# 额外设置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WintermelonC

# 插件
# plugins:
#   - typeset

# 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      check_paths: true
      url_download: true
      url_max_size: 33554432
      url_timeout: 10

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - assets/stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      # type: timeago