# 网站简介
site_name: WintermelonC Docs
site_url: https://mydomain.org/mysite
site_author: WintermelonC
site_description: WinteremelonC 的网页

# github 仓库
repo_url: https://github.com/WintermelonC/WintermelonC_Docs
repo_name: WintermelonC_Docs
edit_uri: edit/main/docs/

# 页面布局
nav:
  - 首页: index.md
  - ZJU: 
    - zju/index.md
    - 通识课程:
      - zju/general_courses/index.md
      - 无线电测向（初级）: zju/general_courses/radio_direction_finding.md
      - 大学物理实验: zju/general_courses/phy_exp.md
      - 创业启程: zju/general_courses/entrepreneurship.md
      - 茶文化与茶健康: zju/general_courses/tea_culture.md
      - 经济法理论与实务: zju/general_courses/economic_law.md
      - 生命科学导论: zju/general_courses/life_science.md
    - 专业基础课程:
      - zju/basic_courses/index.md
      - 概率论与数理统计: 
        - zju/basic_courses/prob_theo_and_math_stat/index.md
        - 2 随机变量及其概率分布: zju/basic_courses/prob_theo_and_math_stat/chapter_2.md
  - 大学生生活常识:
    - common_sense/index.md
    - 医院看病流程: common_sense/hospital.md
    - 医保: common_sense/medical_insurance.md
    - 乘坐交通工具: common_sense/transportation.md

# 主题设置
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换至黑夜模式
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至白天模式
  language: zh
  logo: ./img/logo.png
  favicon: ./img/logo.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

# 额外设置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WintermelonC

# 插件
# plugins:
#   - typeset

# 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      check_paths: true
      url_download: true
      url_max_size: 33554432
      url_timeout: 10

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css