# 网站简介
site_name: WintermelonC Docs
site_url: https://wintermelonc.github.io/WintermelonC_Docs/
site_author: WintermelonC
site_description: WintermelonC 的网页

# github 仓库
repo_url: https://github.com/WintermelonC/WintermelonC_Docs
repo_name: WintermelonC_Docs
edit_uri: edit/main/docs/

# 版权声明
copyright: Copyright &copy; 2024 - 2025 WintermelonC

# 页面布局
nav:
  - 首页: index.md
  - ZJU:
    - zju/index.md
    - 思政类:
      - zju/political/index.md
      - 中国近现代史纲要: zju/political/history_of_modern_china.md
      - 马克思主义基本原理:
        - zju/political/marxist_principles/index.md
        - 0 导论: zju/political/marxist_principles/ch0.md
        - 1 世界的物质性及发展规律: zju/political/marxist_principles/ch1.md
        - 2 实践与认识及其发展规律: zju/political/marxist_principles/ch2.md
        - 3 人类社会及其发展规律: zju/political/marxist_principles/ch3.md
      - 习近平新时代中国特色社会主义思想概论: zju/political/xi_jinping_thought.md
      - 中国共产党历史: zju/political/history_of_CPC.md
    - 军体类:
      - zju/military_PE/index.md
      - 无线电测向（初级）: zju/military_PE/radio_direction_finding.md
      - 羽毛球（初级）: zju/military_PE/badminton.md
      - 游泳（初级）: zju/military_PE/swimming.md
      - 军事理论: zju/military_PE/military_theory.md
    - 计算机类:
      - zju/computer/index.md
      - 人工智能基础（A）: 
        - zju/computer/AI_basic/index.md
        - 1 初识人工智能: zju/computer/AI_basic/ch1.md
        - 2 人工智能的系统数据基础: zju/computer/AI_basic/ch2.md
        - 3 人工智能的应用开发基础: zju/computer/AI_basic/ch3.md
        - 4 从问题求解到机器学习: zju/computer/AI_basic/ch4.md
        - 5 回归与分类模型: zju/computer/AI_basic/ch5.md
        - 6 数据的聚类和降维技术: zju/computer/AI_basic/ch6.md
        - 7 深度网络基础组件: zju/computer/AI_basic/ch7.md
        - 8 卷积神经网络: zju/computer/AI_basic/ch8.md
        - 9 循环神经网络: zju/computer/AI_basic/ch9.md
        - 10 完整的人工智能应用开发实践: zju/computer/AI_basic/ch10.md
        - 11 自然语言处理建模: zju/computer/AI_basic/ch11.md
        - 12 大语言模型与生成式人工智能: zju/computer/AI_basic/ch12.md
        - 习题整理: zju/computer/AI_basic/exercise.md
    - 自然科学通识类:
      - zju/natural_science/index.md
      - 大学物理（乙）Ⅱ: 
        - zju/natural_science/phy_2/index.md
        - 整理: zju/natural_science/phy_2/phy_2_doc.md
      - 大学物理实验: zju/natural_science/phy_exp.md
    - 创新创业类:
      - zju/innovation_entrepreneurship/index.md
      - 创业启程: zju/innovation_entrepreneurship/entrepreneurship.md
    - 通识选修课程:
      - zju/general_courses/index.md
      - 茶文化与茶健康: zju/general_courses/tea_culture.md
      - 经济法理论与实务: zju/general_courses/economic_law.md
      - 生物进化与设计: 
        - zju/general_courses/bio_evolution_and_design/index.md
        - 整理: zju/general_courses/bio_evolution_and_design/doc.md
      - 数字音视频基础与制作: zju/general_courses/digital_audio_video.md
      - 生命科学导论: 
        - zju/general_courses/life_science/index.md
        - 整理: zju/general_courses/life_science/doc.md
        - 1 细胞与细胞工程: zju/general_courses/life_science/ch1.md
        - 2 基因与基因工程: zju/general_courses/life_science/ch2.md
      - 生命科学导论实验: zju/general_courses/life_science_exp.md
      - 无线网络应用:
        - zju/general_courses/wireless_network/index.md
        - 1 当今网络: zju/general_courses/wireless_network/ch1.md
        - 2 交换机和终端设备的基本配置: zju/general_courses/wireless_network/ch2.md
        - 3 协议和模型: zju/general_courses/wireless_network/ch3.md
        - 4 物理层: zju/general_courses/wireless_network/ch4.md
        - 5 数制系统: zju/general_courses/wireless_network/ch5.md
        - 6 数据链路: zju/general_courses/wireless_network/ch6.md
        - 7 以太网交换: zju/general_courses/wireless_network/ch7.md
        - 8 网络层: zju/general_courses/wireless_network/ch8.md
        - 9 地址解析: zju/general_courses/wireless_network/ch9.md
        - 10 路由器基本配置: zju/general_courses/wireless_network/ch10.md
        - 11 IPv4 编址: zju/general_courses/wireless_network/ch11.md
        - 12 IPv6 编址: zju/general_courses/wireless_network/ch12.md
        - 13 ICMP: zju/general_courses/wireless_network/ch13.md
        - 14 传输层: zju/general_courses/wireless_network/ch14.md
        - 15 应用层: zju/general_courses/wireless_network/ch15.md
        - 16 网络安全基础知识: zju/general_courses/wireless_network/ch16.md
        - 17 构建小型网络: zju/general_courses/wireless_network/ch17.md
    - 专业基础课程:
      - zju/basic_courses/index.md
      - 离散数学及其应用: zju/basic_courses/discrete_math.md
      - 数据结构基础: zju/basic_courses/data_structure.md
      - 数字逻辑设计:
        - zju/basic_courses/digital_logic_design/index.md
        - 实验部分:
          - zju/basic_courses/digital_logic_design/lab/index.md
          - final: zju/basic_courses/digital_logic_design/lab/final.md
      - 概率论与数理统计: 
        - zju/basic_courses/prob_theo_and_math_stat/index.md
        - 1 概率论的基本概念: zju/basic_courses/prob_theo_and_math_stat/chapter_1.md
        - 2 随机变量及其概率分布: zju/basic_courses/prob_theo_and_math_stat/chapter_2.md
        - 3 多维随机变量及其分布: zju/basic_courses/prob_theo_and_math_stat/chapter_3.md
        - 4 随机变量的数字特征: zju/basic_courses/prob_theo_and_math_stat/chapter_4.md
        - 5 大数定律及中心极限定律: zju/basic_courses/prob_theo_and_math_stat/chapter_5.md
        - 6 统计量与抽样分布: zju/basic_courses/prob_theo_and_math_stat/chapter_6.md
        - 7 参数估计: zju/basic_courses/prob_theo_and_math_stat/chapter_7.md
        - 8 假设检验: zju/basic_courses/prob_theo_and_math_stat/chapter_8.md
      - 面向对象程序设计:
        - zju/basic_courses/OOP/index.md
        - 0 Introduction: zju/basic_courses/OOP/ch0.md
        - 1 Using Objects: zju/basic_courses/OOP/ch1.md
        - 2 Grouping Objects: zju/basic_courses/OOP/ch2.md
        - 3 Defining Class: zju/basic_courses/OOP/ch3.md
        - 4 Inside Object: zju/basic_courses/OOP/ch4.md
        - 5 Inside Class: zju/basic_courses/OOP/ch5.md
        - 6 Composition: zju/basic_courses/OOP/ch6.md
        - 7 Inheritance: zju/basic_courses/OOP/ch7.md
        - 8 Polymorphism: zju/basic_courses/OOP/ch8.md
        - 9 Copy and Move: zju/basic_courses/OOP/ch9.md
        - 10 Overloaded Operator: zju/basic_courses/OOP/ch10.md
        - 11 Template: zju/basic_courses/OOP/ch11.md
        - 12 Exception: zju/basic_courses/OOP/ch12.md
    - 专业必修课程:
      - zju/compulsory_courses/index.md
      - 高级数据结构与算法分析:
        - zju/compulsory_courses/ADS/index.md
        - 1 AVL Trees, Splay Trees and Amortized Analysis: zju/compulsory_courses/ADS/ch1.md
        - 2 Red-Black Trees and B+ Trees: zju/compulsory_courses/ADS/ch2.md
        - 3 Inverted File Index: zju/compulsory_courses/ADS/ch3.md
        - 4 Leftist Heaps and Skew Heaps: zju/compulsory_courses/ADS/ch4.md
        - 5 Binomial Queues: zju/compulsory_courses/ADS/ch5.md
        - 6 Backtracking: zju/compulsory_courses/ADS/ch6.md
        - 7 Divide and Conquer: zju/compulsory_courses/ADS/ch7.md
        - 8 Dynamic Programming: zju/compulsory_courses/ADS/ch8.md
        - 9 Greedy Algorithms: zju/compulsory_courses/ADS/ch9.md
        - 10 Intractability: zju/compulsory_courses/ADS/ch10.md
        - 11 Approximation Algorithms: zju/compulsory_courses/ADS/ch11.md
        - 12 Local Search: zju/compulsory_courses/ADS/ch12.md
        - 13 Randomized Algorithms: zju/compulsory_courses/ADS/ch13.md
        - 14 Parallel Algorithms: zju/compulsory_courses/ADS/ch14.md
        - 15 External Sorting: zju/compulsory_courses/ADS/ch15.md
      - 计算机组成:
        - zju/compulsory_courses/computer_organization/index.md
        - 理论部分: 
          - 1 Computer Abstractions and Technology: zju/compulsory_courses/computer_organization/theory/ch1.md
          - '2 Instructions: Language of the Computer': zju/compulsory_courses/computer_organization/theory/ch2.md
          - 3 Arithmetic for Computers: zju/compulsory_courses/computer_organization/theory/ch3.md
          - 4 The Processor: zju/compulsory_courses/computer_organization/theory/ch4.md
          - '5 Large and Fast: Exploiting Memory Hierarchy': zju/compulsory_courses/computer_organization/theory/ch5.md
          - 6 Storage and Other I/O Topics: zju/compulsory_courses/computer_organization/theory/ch6.md
        - 实验部分:
          - zju/compulsory_courses/computer_organization/lab/index.md
          - 'Lab 0: Vivado 介绍与模块封装': zju/compulsory_courses/computer_organization/lab/lab0.md
          - 'Lab 1: ALU、Regfiles 设计与有限状态机': zju/compulsory_courses/computer_organization/lab/lab1.md
          - 'Lab 2: CPU 调试 SOC 系统设计': zju/compulsory_courses/computer_organization/lab/lab2.md
          - 'Lab 3: 复杂操作实现': zju/compulsory_courses/computer_organization/lab/lab3.md
          - 'Lab 4: 单周期 CPU': zju/compulsory_courses/computer_organization/lab/lab4.md
          - 'Lab 5: 流水线 CPU': zju/compulsory_courses/computer_organization/lab/lab5.md
      - 数据库系统:
        - zju/compulsory_courses/database_system/index.md
        - 1 Introduction: zju/compulsory_courses/database_system/ch1.md
        - 2 Introduction to the Relational Model: zju/compulsory_courses/database_system/ch2.md
        - 3 Introduction to SQL: zju/compulsory_courses/database_system/ch3.md
        - 4 Advanced SQL: zju/compulsory_courses/database_system/ch4.md
        - 5 Entity-Relationship Model: zju/compulsory_courses/database_system/ch5.md
        - 6 Relational Database Design: zju/compulsory_courses/database_system/ch6.md
        - 7 Storage and File Structure: zju/compulsory_courses/database_system/ch7.md
        - 8 Indexing and Hashing: zju/compulsory_courses/database_system/ch8.md
        - 9 Query Processing: zju/compulsory_courses/database_system/ch9.md
        - 10 Query optimization: zju/compulsory_courses/database_system/ch10.md
        - 11 Transactions: zju/compulsory_courses/database_system/ch11.md
        - 12 Concurrency Control: zju/compulsory_courses/database_system/ch12.md
      - 计算机体系结构:
        - zju/compulsory_courses/computer_architecture/index.md
        - 理论部分:
          - 1 Fundamentals of Quantitative Design and Analysis: zju/compulsory_courses/computer_architecture/theory/ch1.md
          - '2 Pipelining: Basic and Intermediate Concepts': zju/compulsory_courses/computer_architecture/theory/ch2.md
          - 3 Memory Hierarchy Design: zju/compulsory_courses/computer_architecture/theory/ch3.md
          - 4 Instruction-Level Parallelism and Its Exploitation: zju/compulsory_courses/computer_architecture/theory/ch4.md
          - 5 Data-Level Parallelism in Vector, SIMD, and GPU Architectures: zju/compulsory_courses/computer_architecture/theory/ch5.md
        - 实验部分:
          - zju/compulsory_courses/computer_architecture/lab/index.md
    - 专业模块课程:
      - zju/module_courses/index.md
      - 密码学:
        - zju/module_courses/cryptography/index.md
        - 1 数学基础: zju/module_courses/cryptography/ch1.md
        - 2 古典密码: zju/module_courses/cryptography/ch2.md
        - 3 Hash 函数: zju/module_courses/cryptography/ch3.md
        - 4 分组密码工作模式与流密码: zju/module_courses/cryptography/ch4.md
        - 5 DES 算法和 AES 算法: zju/module_courses/cryptography/ch5.md
        - 6 RSA 算法: zju/module_courses/cryptography/ch6.md
    - 实践教学环节:
      - zju/practical_teaching/index.md
      - 课程综合实践Ⅰ: zju/practical_teaching/practical_course_1.md
    - 个性修读课程:
      - zju/personal_courses/index.md
      - 有机化学:
        - zju/personal_courses/organic_chemistry/index.md
        - 1 有机化合物分子结构基础: zju/personal_courses/organic_chemistry/ch1.md
        - 2 脂肪烃和脂环烃: zju/personal_courses/organic_chemistry/ch2.md
  - 大学生生活常识:
    - common_sense/index.md
    - 医院看病流程: common_sense/hospital.md
    - 医保: common_sense/medical_insurance.md
    - 如何乘坐交通工具: common_sense/transportation.md
    - 租房流程及注意事项: common_sense/rent.md
    - 做饭的基本逻辑: common_sense/cooking.md
    - 行政服务办理流程: common_sense/administrative_service.md
    - 如何写简历: common_sense/resume.md
  - 软件:
    - application/index.md
    - Br:
      - application/br/index.md
      - 1 首选项: application/br/ch1.md
      - 2 基本操作: application/br/ch2.md
      - 3 文件整理/归纳/筛选: application/br/ch3.md
    - Ps:
      - application/ps/index.md
    - Pr:
      - application/pr/index.md
      - 插件: application/pr/plugins.md
    - Ae:
      - application/ae/index.md
      - 插件: application/ae/plugins.md
      - 其他:
        - 物体阴影: application/ae/other/shadow.md
    - Vivado: 
      - application/vivado/index.md
    - VS Code:
      - application/vscode/index.md
      - Github Copilot: application/vscode/copilot.md
    - Watt Toolkit:
      - application/watt_toolkit/index.md
  - 知识:
    - knowledge/index.md
    - Python:
      - knowledge/python/index.md
      - Anaconda: knowledge/python/anaconda.md
      - Python 编程基础:
        - knowledge/python/basic/index.md
        - 0 Python 环境及编辑器: knowledge/python/basic/ch0.md
        - 1 Python 基础: knowledge/python/basic/ch1.md
        - 2 控制流: knowledge/python/basic/ch2.md
        - 3 函数: knowledge/python/basic/ch3.md
        - 4 列表: knowledge/python/basic/ch4.md
        - 5 字典和结构化数据: knowledge/python/basic/ch5.md
      - PyTorch 深度学习:
        - knowledge/python/pytorch/index.md
        - 7 现代卷积神经网络:
          - 7.1 AlexNet 深度卷积神经网络: knowledge/python/pytorch/ch7/ch7_1.md
          - 7.2 VGG 使用块的网络: knowledge/python/pytorch/ch7/ch7_2.md
          - 7.3 NiN 网络中的网络: knowledge/python/pytorch/ch7/ch7_3.md
          - 7.4 GoogLeNet 含并行连结的网络: knowledge/python/pytorch/ch7/ch7_4.md
          - 7.5 批量规范化: knowledge/python/pytorch/ch7/ch7_5.md
          - 7.6 ResNet 残差网络: knowledge/python/pytorch/ch7/ch7_6.md
          - 7.7 DenseNet 稠密连接网络: knowledge/python/pytorch/ch7/ch7_7.md
        - 8 循环神经网络:
          - 8.1 序列模型: knowledge/python/pytorch/ch8/ch8_1.md
          - 8.2 文本预处理: knowledge/python/pytorch/ch8/ch8_2.md
          - 8.3 语言模型和数据集: knowledge/python/pytorch/ch8/ch8_3.md
          - 8.4 循环神经网络: knowledge/python/pytorch/ch8/ch8_4.md
    - C/C++:
      - knowledge/C_Cpp/index.md
    - Web:
      - knowledge/web/index.md
      - HTML: knowledge/web/html.md
      - CSS: knowledge/web/css.md
      - JavaScript: knowledge/web/javascript.md
    - Markdown: 
      - knowledge/markdown/index.md
    - 数据结构与算法:
      - knowledge/data_stru_algorithm/index.md
      - 其他:
        - 埃拉托斯特尼筛法求质数: knowledge/data_stru_algorithm/other/sieve_of_eratosthenes.md
  - 工具:
    - tools/index.md
    - Git:
      - tools/git/index.md
      - 1 安装与配置: tools/git/ch1.md
      - 2 基本操作: tools/git/ch2.md
      - 3 分支操作: tools/git/ch3.md
      - 4 远程操作: tools/git/ch4.md
      - 5 多人协作: tools/git/ch5.md
    - Github:
      - tools/github/index.md
      - Github Pages:
        - tools/github/github_pages/index.md
    - MkDocs:
      - tools/mkdocs/index.md
      - Material for MkDocs:
        - tools/mkdocs/material/index.md
        - 1 预备工作: tools/mkdocs/material/ch1.md
        - 2 简单使用: tools/mkdocs/material/ch2.md
        - 3 发布网站: tools/mkdocs/material/ch3.md
        - 4 探索配置: tools/mkdocs/material/ch4.md
        - 5 深度理解: tools/mkdocs/material/ch5.md

# 主题设置
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: 切换至深色主题
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: 切换至浅色主题
  language: zh
  logo: ./img/logo.png
  favicon: ./img/logo.png
  icon:
    repo: fontawesome/brands/github
    annotation: material/plus-circle
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# 扩展
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
      toc_depth: 4
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      check_paths: true
      url_download: true
      url_max_size: 33554432
      url_timeout: 10

# 额外设置
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WintermelonC
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1089287731

# 额外 js
extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

# 额外 css
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - assets/stylesheets/extra.css?v=1.0.2
  - assets/stylesheets/hqcard.css?v=1.0.0
  - assets/stylesheets/bootstrap.css?v=1.0.0

# 插件
plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      # type: timeago